Use shasum command and better error handling

diff --git a/hugow b/hugow
--- a/hugow
+++ b/hugow
@@ -148,6 +148,12 @@ parse_json() {
     echo ${temp##*|} | sed "s/${field}: //g"
 }
 
+remove_file() {
+    if [ -n "$1" -a "$1" != "/" -a -f "$1" -a -r "$1" ] ; then
+        rm "$1"
+    fi
+}
+
 download_version() {
     versionToDownload="$1"
 
@@ -174,30 +180,43 @@ download_version() {
         $DOWNLOAD_COMMAND $DOWNLOAD_SILENT $DOWNLOAD_OUTPUT "$tarballPath" "$binaryUrl" &
         $DOWNLOAD_COMMAND $DOWNLOAD_SILENT $DOWNLOAD_OUTPUT "$checksumPath" "$checksumUrl" &
         wait
-        printf "[done]\n"
+
+        if [ -s "$tarballPath" -a -s "$checksumPath" ]; then
+            printf "[done]\n"
+        else
+            printf "[failed]\n"
+            remove_file "$checksumPath"
+            remove_file "$tarballPath"
+            exit 1
+        fi
 
         printf "verifying hugo binary version v${versionToDownload} ..... "
-        cd $BASE_DIR/.hugo/ && sha256sum --ignore-missing --check "$checksumName" > /dev/null && cd - > /dev/null 2>&1 &
+        cd $BASE_DIR/.hugo/
+        grep "${tarballName}" "$BASE_DIR/.hugo/$checksumName" | shasum --algorithm 256 --check > /dev/null
+        cd - > /dev/null 2>&1
         wait
         printf "[done]\n"
 
         printf "unzipping hugo binary version v${versionToDownload} ..... "
-        tar --directory="$BASE_DIR/.hugo/" -xzf "$tarballPath" &
-        wait
-        printf "[done]\n"
-
-        # delete checksum file
-        if [ -n "$checksumPath" -a "$checksumPath" != "/" ] ; then
-            rm "$checksumPath"
+        if [ -f "${tarballPath}" -a -r "${tarballPath}" ]; then
+            tar --directory="$BASE_DIR/.hugo/" -xzf "${tarballPath}" 2>&1
+            wait
+            printf "[done]\n"
+        else
+            printf "[failed]\n"
+            remove_file "$checksumPath"
+            remove_file "$tarballPath"
+            exit 1
         fi
 
         # save the downloaded binary version into $BASE_DIR/.hugo/version
         echo "$versionToDownload" > $BASE_DIR/.hugo/version
 
         # cleanup after extraction
-        rm "$BASE_DIR/.hugo/${tarballName}"
-        rm "$BASE_DIR/.hugo/LICENSE"
-        rm "$BASE_DIR/.hugo/README.md"
+        remove_file "$checksumPath"
+        remove_file "$tarballPath"
+        remove_file "$BASE_DIR/.hugo/LICENSE"
+        remove_file "$BASE_DIR/.hugo/README.md"
     fi
 }
 
@@ -212,14 +231,18 @@ if [ -r "$BASE_DIR/.hugo/hugo" ]; then
         if [ "$get_version" != "$current_binary_version" ]; then
             # specified hugo version
             download_version "$get_version"
+        else
+            echo "hugo binary version $get_version already exists"
         fi
      elif [ $get_latest = true ]; then
-        latest_release=`$DOWNLOAD_COMMAND $DOWNLOAD_SILENT https://api.github.com/repos/gohugoio/hugo/releases/latest`
+        latest_release=`$DOWNLOAD_COMMAND $DOWNLOAD_SILENT ${DOWNLOAD_OUTPUT}- https://api.github.com/repos/gohugoio/hugo/releases/latest`
         latest_version=`parse_json "$latest_release" "tag_name" | sed -ne 's/[^0-9]*\(\([0-9]*\.\)\{0,4\}[0-9]*[^.]\).*/\1/p'`
 
         if [ "$latest_version" != "$current_binary_version" ]; then
             # latest hugo version
-            download_version "LATEST"
+            download_version "$latest_version"
+        else
+            echo "latest hugo binary version $latest_version already exists"
         fi
     elif [ -r "$BASE_DIR/.hugo/version" ]; then
         current_file_version="$(cat "$BASE_DIR/.hugo/version")"
@@ -252,6 +275,7 @@ fi
 # only download binary and not execute hugo related command
 # ----------------------------------------------------------------------------
 if [ "$get_latest" = true -o -n "$get_version" ]; then
+    ${BASE_DIR}/.hugo/hugo version
     exit
 fi
 
